In [1]:
# This code generates 20 specific and 30 random configurations
import numpy as np
import shutil
import os
from google.colab import drive
drive.mount('/content/drive')

# 4 signature configurations for the 18 qubits.
S0 = np.array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
               [-1, +1, -1, -1, -1, -1, -1, +1, -1, -1, -1, -1, -1, +1, -1, -1, -1, -1],
               [-1, -1, -1, -1, -1, -1, -1, -1, -1, +1, +1, +1, -1, -1, -1, -1, -1, -1],
               [-1, +1, -1, -1, -1, -1, -1, +1, -1, +1, +1, +1, -1, +1, -1, -1, -1, -1]])

D1 = np.diag([-1, -1, +1, +1, +1, +1, -1, -1, +1, +1, +1, +1, -1, -1, +1, +1, +1, +1])
D2 = np.diag([+1, -1, -1, +1, +1, +1, +1, -1, -1, +1, +1, +1, +1, -1, -1, +1, +1, +1])
D3 = np.diag([+1, +1, +1, -1, -1, -1, +1, +1, +1, -1, -1, -1, +1, +1, +1, +1, +1, +1])
D4 = np.diag([+1, +1, +1, +1, +1, +1, +1, +1, +1, -1, -1, -1, +1, +1, +1, -1, -1, -1])

tem = [[],[],[],[]]
for i in range(4):
    tem[i]=np.vstack((np.dot(S0[i], D1),np.dot(S0[i], D2),np.dot(S0[i], D3),np.dot(S0[i], D4)))
SA = np.vstack((tem[0], tem[1], tem[2], tem[3]))

np.random.seed(1)
S10000 = np.random.choice([-1, 1], size=(10000, 18))
SB = S10000[0:30]

S20_30 = np.vstack((S0,SA,SB))
print(len(S20_30))
print(S20_30)

def count_identical_rows(matrix):
    # Find unique rows and their counts
    unique_rows, counts = np.unique(matrix, axis=0, return_counts=True)

    # Filter rows that appear more than once and return their counts
    duplicated_rows = unique_rows[counts > 1]
    duplicated_counts = counts[counts > 1]

    return dict(zip(map(tuple, duplicated_rows), duplicated_counts))


# there is no reduplicate configuration.
print("reduplicate configurations:", count_identical_rows(S20_30))
np.save('S20_30.npy', S20_30)
shutil.move('S20_30.npy', '/content/drive/My Drive/Toric Code 2D/3: FRRBM on 3x3/Data/S20_30.npy')

Mounted at /content/drive
50
[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1 -1 -1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1 -1  1 -1  1  1  1 -1  1 -1 -1 -1 -1]
 [ 1  1 -1 -1 -1 -1  1  1 -1 -1 -1 -1  1  1 -1 -1 -1 -1]
 [-1  1  1 -1 -1 -1 -1  1  1 -1 -1 -1 -1  1  1 -1 -1 -1]
 [-1 -1 -1  1  1  1 -1 -1 -1  1  1  1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1 -1 -1 -1  1  1  1]
 [ 1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1]
 [-1 -1  1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1 -1 -1 -1]
 [-1  1 -1  1  1  1 -1  1 -1  1  1  1 -1  1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1 -1  1 -1  1  1  1 -1  1 -1  1  1  1]
 [ 1  1 -1 -1 -1 -1  1  1 -1  1  1  1  1  1 -1 -1 -1 -1]
 [-1  1  1 -1 -1 -1 -1  1  1  1  1  1 -1  1  1 -1 -1 -1]
 [-1 -1 -1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1]
 [ 1 -1 -1 -1 -1 -1  1 -1 -1  1  1  1  1 -1 -1 -1 -1 -1]
 [

'/content/drive/My Drive/Toric Code 2D/3: FRRBM on 3x3/Data/S20_30.npy'

In [ ]:
# This code generates 10000 random configurations
import numpy as np
import shutil
import os
from google.colab import drive
drive.mount('/content/drive')

np.random.seed(1)
S10000 = np.random.choice([-1, 1], size=(10000, 18))
print(S10000)


def count_identical_rows(matrix):
    # Find unique rows and their counts
    unique_rows, counts = np.unique(matrix, axis=0, return_counts=True)

    # Filter rows that appear more than once and return their counts
    duplicated_rows = unique_rows[counts > 1]
    duplicated_counts = counts[counts > 1]
    # Sum of all the duplicated counts
    total= sum(duplicated_counts)

    return {'total duplicated': total,
        'duplicated rows': dict(zip(map(tuple, duplicated_rows), duplicated_counts))}

# there is 358 reduplicate configurations.
print("reduplicate configurations:", count_identical_rows(S10000))
np.save('S10000.npy', S10000)
shutil.move('S10000.npy', '/content/drive/My Drive/Toric Code 2D/3: FRRBM on 3x3/Data/S10000.npy')