In [ ]:
import numpy as np
import shutil
import os
from google.colab import drive
drive.mount('/content/drive')

Variables9 = np.round(np.random.uniform(-3.15, 3.15, size=(1000, 9)), 2)

def count_identical_rows(matrix):
    # Find unique rows and their counts
    unique_rows, counts = np.unique(matrix, axis=0, return_counts=True)

    # Filter rows that appear more than once and return their counts
    duplicated_rows = unique_rows[counts > 1]
    duplicated_counts = counts[counts > 1]

    return dict(zip(map(tuple, duplicated_rows), duplicated_counts))

print(Variables9)
# there is no reduplicate configuration.
print("reduplicate configurations:", count_identical_rows(Variables9))
np.save('Variables9.npy', Variables9)
shutil.move('Variables9.npy', '/content/drive/My Drive/Toric Code 2D/3: FRRBM on 3x3/Data/Variables9_1k.npy')

Mounted at /content/drive
[[-2.84  0.83  1.12 ... -2.27  2.48  3.04]
 [ 0.36 -1.34  0.95 ...  1.38 -0.74  0.93]
 [ 3.08  1.79 -2.17 ... -0.06  2.78  2.58]
 ...
 [-2.72  0.41 -1.69 ...  2.78 -1.98 -2.03]
 [-2.65  1.34 -0.47 ...  1.25 -1.87  2.95]
 [ 0.23 -1.11 -0.49 ... -2.61  2.78  0.37]]
reduplicate configurations: {}


'/content/drive/My Drive/Toric Code 2D/3: FRRBM on 3x3/Data/Variables9_1.npy'

In [ ]:
import numpy as np
import shutil
import os
from google.colab import drive
drive.mount('/content/drive')

Variables10 = np.round(np.random.uniform(-3.15, 3.15, size=(1000, 10)), 2)

def count_identical_rows(matrix):
    # Find unique rows and their counts
    unique_rows, counts = np.unique(matrix, axis=0, return_counts=True)

    # Filter rows that appear more than once and return their counts
    duplicated_rows = unique_rows[counts > 1]
    duplicated_counts = counts[counts > 1]

    return dict(zip(map(tuple, duplicated_rows), duplicated_counts))

print(Variables10)
# there is no reduplicate configuration.
print("reduplicate configurations:", count_identical_rows(Variables10))
np.save('Variables10.npy', Variables10)
shutil.move('Variables10.npy', '/content/drive/My Drive/Toric Code 2D/3: FRRBM on 3x3/Data/Variables10_1k.npy')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[[ 2.24  2.06  1.85 ... -2.97  1.99 -1.58]
 [ 2.9   0.31  0.35 ...  0.08  0.87  3.14]
 [ 1.89 -1.66 -1.01 ... -1.63 -1.44  0.76]
 ...
 [-0.88 -2.35  0.22 ... -2.91  1.12 -1.5 ]
 [ 2.15  2.22 -2.79 ...  1.21  1.45 -0.05]
 [-2.42  2.27  1.03 ...  3.15 -0.12  1.63]]
reduplicate configurations: {}


'/content/drive/My Drive/Toric Code 2D/3: FRRBM on 3x3/Data/Variables10_1.npy'

In [ ]:
import numpy as np
import shutil
import os
from google.colab import drive
drive.mount('/content/drive')

np.random.seed(1)
Variables10extra = np.round(np.random.uniform(-3.15, 3.15, size=(10000, 10)), 2)

def count_identical_rows(matrix):
    # Find unique rows and their counts
    unique_rows, counts = np.unique(matrix, axis=0, return_counts=True)

    # Filter rows that appear more than once and return their counts
    duplicated_rows = unique_rows[counts > 1]
    duplicated_counts = counts[counts > 1]

    return dict(zip(map(tuple, duplicated_rows), duplicated_counts))

print(Variables10extra)
# there is no reduplicate configuration.
print("reduplicate configurations:", count_identical_rows(Variables10extra))
np.save('Variables10extra.npy', Variables10extra)
shutil.move('Variables10extra.npy', '/content/drive/My Drive/Toric Code 2D/3: FRRBM on 3x3/Data/Variables10_10k.npy')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[[-0.52  1.39 -3.15 ... -0.97 -0.65  0.24]
 [-0.51  1.17 -1.86 ...  0.37 -2.27 -1.9 ]
 [ 1.89  2.95 -1.18 ... -2.9  -2.08  2.38]
 ...
 [ 1.22  2.05  1.64 ... -3.01 -1.5  -0.2 ]
 [-3.1  -2.41 -0.61 ...  0.83  1.41 -1.  ]
 [ 0.55  1.66  3.14 ...  2.    0.43  0.71]]
reduplicate configurations: {}


'/content/drive/My Drive/Toric Code 2D/3: FRRBM on 3x3/Data/Variables10_10.npy'