In [ ]:
import numpy as np
import shutil
import os
from google.colab import drive
drive.mount('/content/drive')

part1 = np.round(np.random.uniform(-3.15, 3.15, size=(1000, 5)), 2)
part2 = np.round(np.random.uniform(-1.58, 1.58, size=(1000, 6)), 2)
Variables = np.hstack((part1, part2))

def count_identical_rows(matrix):
    # Find unique rows and their counts
    unique_rows, counts = np.unique(matrix, axis=0, return_counts=True)

    # Filter rows that appear more than once and return their counts
    duplicated_rows = unique_rows[counts > 1]
    duplicated_counts = counts[counts > 1]

    return dict(zip(map(tuple, duplicated_rows), duplicated_counts))

print(Variables)
# there is no reduplicate configuration.
print("reduplicate configurations:", count_identical_rows(Variables))
np.save('Variables.npy', Variables)
shutil.move('Variables.npy', '/content/drive/My Drive/Toric Code 2D/6: RBM on 3x3/Data/Variables.npy')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[[-2.95 -3.03 -0.86 ... -0.51 -0.98  1.55]
 [-2.41 -2.12  1.9  ...  0.35  1.09  0.48]
 [-2.44 -1.59  3.05 ...  0.29  1.29  0.35]
 ...
 [-1.06  0.38 -2.35 ... -0.32  1.08  0.27]
 [ 1.62  1.92 -1.98 ...  0.48  1.05  0.61]
 [-0.04 -0.36  0.32 ...  1.21  0.14  0.7 ]]
reduplicate configurations: {}


'/content/drive/My Drive/Toric Code 18 qubits/Nonlocal/Variables.npy'